### ISSUE TITLE
Feature request: LRU cache to prevent duplicate minificiation

### ISSUE THREAD

**Issue by dotnetchris** [trullock/NUglify#1]
A fairly common scenario is directly injecting an asynchronous javascript loader into the markup of a page to eliminate network round trips. Commonly this code will be statically determined and as such could be minified once for the lifetime of the application.

It would be great to be able to support auto caching of minification operations (perhaps with an opt-in `cache: true` overload). Since developers will either intentionally or inadvertently also end up caching dynamic javascript (like including userid in the text making it unique per user) at some point it could lead to a large amount of memory consumption that would be unexpected.

Using a LRU cache that continually prunes uncommonly accessed items would provide a simple way to limit memory consumption or to specifically require users to opt-in to unbounded memory caching.

The naive solution would be to use the whole string input as a key to the cache. However i'm not sure how much risk there is to a hash collision between "large" strings. I'm not sure off hand what alternatives there are to uniquely identifying text that would also cost substantially less than the minimization computation.

**Comment by dotnetchris** [comment]
For simple LRU usage i've always used https://github.com/csharptest/CSharpTest.Net.Collections/blob/master/src/CSharpTest.Net.Collections/Collections/LurchTable.cs (via nuget) it is permissively licensed that it could be linked or embedded as a first party type.

**Comment by xoofx** [comment]
Hi,
Thanks for the suggestion. I'm not sure that would be a good fit to add this kind of scenarios to the library. So far, the library is quite stateless and provides only functions to minify content without higher level handling. I leave the issue open, if more people are looking to solve a similar problem, we could reconsider it.

**Comment by trullock** [comment]
I think this sits outside of Nuglify's scope.
Gonna close this. If its anyone's got a good counter argument or PR I'll reconsider :)
