### ISSUE TITLE
NUglifyBundleTask and source maps

### ISSUE THREAD

**Issue by dazinator** [trullock/NUglify#11]
Thanks for producing  a great library.

I was just looking into bundling / concatenation of multiple scripts and I saw this: the `NUglifyBundleTask` but I noticed that it doesn't support sourcemaps is that correct? I was just wondering are you aware of any .NET solution for combining individual files that have their own sourcemaps, into a single file but maintaining a valid sourcemap?

**Comment by dazinator** [comment]
Here is something that looks interesting around this: https://github.com/benmccallum/AspNetBundling/blob/master/AspNetBundling/ScriptWithSourceMapBundleBuilder.cs

**Comment by trullock** [comment]
@dazinator https://github.com/microsoft/sourcemap-toolkit is what you want. Theres an example use case of exactly what youre talking about here: https://github.com/trullock/MustardBlackCore/blob/master/MustardBlack.Assets.Javascript.Babel/BabelJavascriptPreprocessor.cs

Not sure if this should be a NUglify feature or not...

**Comment by dazinator** [comment]
Thanks @trullock I will take a look at that!
