### ISSUE TITLE
Can not minify double asterisk (**) operator.

### ISSUE THREAD

**Issue by supershowwei** [trullock/NUglify#118]
`**` is the exponentiation operator introduced in ECMAScript 2016 (ES7) and is the equivalent of Math.pow. But it will occur `Expected expression: *` error message when minification.

Example
```js
const abc = 10 ** 2;
```

**Comment by trullock** [comment]
this should fix your issue, any change you can give this a test?

**Comment by supershowwei** [comment]
test pass. thx.

**Comment by trullock** [comment]
Fixed in 1.6.5
