### ISSUE TITLE
HtmlToText drops text when the only html present is a closing tag

### ISSUE THREAD

**Issue by wayneseguin** [trullock/NUglify#119]
Example: "This is a fragment`</p>`"

HtmlToText should return "This is a fragment", but instead returns an empty string.

I believe the reason is the Write mechanism requires a "body" tag in the output so that it will set outputEnabled to true.

**Comment by wayneseguin** [comment]
Further research shows it will drop ALL text prior to the closing tag 

`This is a fragment </p> and it continues here <a>`  returns `and it continues here `

**Comment by trullock** [comment]
Both our PRs result in the outputted Text being `This is a fragmentand it continues here`, which is not ideal. Reason being that the minifier removes the rogue closing P tag, then the to-stringer simply butts the two text nodes up to each other.

This is kind of correct, but probably not desired?

I think its acceptable for now, the HTML is invalid in the first place.

**Comment by trullock** [comment]
Right, much nicer fix, improved handling of rogue closing tags

**Comment by trullock** [comment]
Shipped in 1.9.1
