### ISSUE TITLE
Indent CSS and JS properly when prettifying HTML

### ISSUE THREAD

**Issue by trullock** [trullock/NUglify#174]
Well it does work, partially

![image](https://user-images.githubusercontent.com/15063294/96897783-41197b80-148f-11eb-9c26-9bf973db7059.png)

![image](https://user-images.githubusercontent.com/15063294/96897277-b89adb00-148e-11eb-87a2-66bfeb7f5e5e.png)

```powershell
    $Settings = [NUglify.Html.HtmlSettings]::new()
    $Settings.RemoveOptionalTags = $false
    $Settings.PrettyPrint = $true
    $Settings.JsSettings.MinifyCode = $false
    $Settings.JsSettings.OutputMode = [NUglify.OutputMode]::MultipleLines
    $Settings.CssSettings.IndentSize = 4
    $Settings.CssSettings.OutputMode = [NUglify.OutputMode]::MultipleLines
    [NUglify.Uglify]::Html($Content, $Settings).Code
```

Those are the settings I use (excuse PowerShell). I would expect code inside the script to start code at the proper position relative to the script tag, same for css. Is this possible?

_Originally posted by @PrzemyslawKlys in https://github.com/trullock/NUglify/issues/168#issuecomment-714588376_

**Comment by trullock** [comment]
@PrzemyslawKlys can you review the PR and see if it works for you?

**Comment by PrzemyslawKlys** [comment]
The test looks correct, although it would be useful to check how it behaves on a minified code where one line is prettified into multiple lines. Maybe misalign <script> tag in input, as at the moment it looks like it just doesn't require to change position.

**Comment by trullock** [comment]
Do you want to add a 2nd test that demonstrates what you mean? cheers

**Comment by PrzemyslawKlys** [comment]
Your test fails for me on Windows because of new lines. 

  Message: 
      Expected string length 183 but was 170. Strings differ at index 0.
      Expected: "\r\n<html>\r\n\t<head>\r\n\t\t<script>\r\n\t\t\tlet x = 1; \r\n\t\t\tlet y = fun..."
      But was:  "\n<html>\n\t<head>\n\t\t<script>\n\t\t\tlet x = 1; \r\n\t\t\tlet y = functio..."
      ------------^

Or am I doing something wrong?

**Comment by PrzemyslawKlys** [comment]
![image](https://user-images.githubusercontent.com/15063294/97565071-e380b400-19e5-11eb-8600-3c6e10ea41b2.png)
![image](https://user-images.githubusercontent.com/15063294/97565105-f0050c80-19e5-11eb-9b61-aa0be13314a3.png)

Basically all tests based on new lines fail on Windows.


  Message: 
      Expected string length 38 but was 39. Strings differ at index 16.
      Expected: "var testString=`\n`+`} async init(){ }`"
      But was:  "var testString=`\r\n`+`} async init(){ }`"
      ----------------------------^

**Comment by trullock** [comment]
I know whats happening but not why.

Can you list me all the failing tests, as I can't repro this

**Comment by PrzemyslawKlys** [comment]
I guess you're running the tests on Mac or Linux. 

https://superuser.com/questions/374028/how-are-n-and-r-handled-differently-on-linux-and-windows

My guess is, as part of your code inserting `[Environment]::NewLine` or similar. In Windows, it will be \r\n, but in Linux, it will be just \n. Therefore your test works fine on one system, but not the other. You would need to propose a test that would take this into consideration. From "works as designed" perspective - it works fine. Just test fails I guess.

**Comment by trullock** [comment]
No I'm on Windows, and so is AppVeyor which also passes

**Comment by trullock** [comment]
My suspicion is that your git settings are modifying line endings on checkout, could this be the case?

**Comment by trullock** [comment]
Closing this because its fixed. If there are line ending bugs, they have always existed and are therefore outside the scope of this issue.

Please make a new issue if you can determine why your environment is behaving like this ^

Otherwise, see `1.9.11` for your requested fixes :)

**Comment by PrzemyslawKlys** [comment]
Thank you for your improvement. I'll open a new issue, maybe more details will help.
