### ISSUE TITLE
Three Tests are failing because of NewLine differences

### ISSUE THREAD

**Issue by PrzemyslawKlys** [trullock/NUglify#177]
It's a continuation of problems with Tests failing because of new lines (https://github.com/trullock/NUglify/issues/174).

What I did (also did just now) is going to the GitHub Code page choose  Open in Visual Studio, it opened VS, downloaded everything, I told it to rebuild the project, it did, and when I rerun tests with 0 modifications

![image](https://user-images.githubusercontent.com/15063294/98443482-deb9af80-210b-11eb-83e3-f9bda309ef90.png)

3 tests are failing, those with new lines only. Then I open up VSCode as I am a bit more familiar with it and it shows proper CRLF

![image](https://user-images.githubusercontent.com/15063294/98443620-b54d5380-210c-11eb-8abc-15cb1463c3c6.png)

I am not sure why it fails, but it does fail for me. I don't have any specific configuration, not I do any commit or changes, just download + run.

**Comment by PrzemyslawKlys** [comment]
I wonder if it matters? 

![image](https://user-images.githubusercontent.com/15063294/98485520-532d4500-2217-11eb-8fef-007125ef3b9e.png)

**Comment by PrzemyslawKlys** [comment]
In the new version, I only see 1 failure so you did some changes right? 

![image](https://user-images.githubusercontent.com/15063294/99182721-fc53ce00-2736-11eb-9d44-3e0e711ea0a8.png)

I also see one can set LineTerminator for JSSettings and CSSSettings but it's not exposed in HTML settings

![image](https://user-images.githubusercontent.com/15063294/99182661-79cb0e80-2736-11eb-88d8-bdee913ebb7d.png)

I'm trying to build some testing for my PSParseHTML which uses your NUglify and it's having exactly the same issue:

![image](https://user-images.githubusercontent.com/15063294/99182691-b565d880-2736-11eb-89c9-e452e788bc65.png)

I am trying to set the tests properly for myself and I will also be testing it within Azure on Windows/Linux/macOS so I expect to have even bigger problems with line feeds.

**Comment by trullock** [comment]
Are you sure you Git and/or Visual Studio settings aren't set to modify line endings?

**Comment by PrzemyslawKlys** [comment]
I don't see how - the only thing I know is I use older git `git version 2.23.0.windows.1` due to bugs in later git where it doesn't work properly in VSCode in paths that are symlinks. Other than that my VS doesn't have any configuration.
