### ISSUE TITLE
Indenting consistency between HTML,JS and CSS

### ISSUE THREAD

**Issue by PrzemyslawKlys** [trullock/NUglify#181]
Thank you for working on all those prettify stuff - I really appreciate it. It's really great and I understand a bit out of the scope of this project, but soon you can change the description from modification tool to prettify/minification tool in one 👍 

You've added the ability to set proper indent for HTML but it's a bit inconsistent for JS/CSS code where it's IndentSize instead.

```powershell
    $Settings = [NUglify.Html.HtmlSettings]::new()
    $Settings.RemoveOptionalTags = $false
    $Settings.PrettyPrint = $true
    $Settings.Indent = "`t"
    $Settings.OutputTextNodesOnNewLine = $false # option to not indent textnodes when theyre the only child
    $Settings.JsSettings.MinifyCode = $true
    $Settings.JsSettings.OutputMode = [NUglify.OutputMode]::MultipleLines
    $Settings.CssSettings.IndentSize = 4
    $Settings.CssSettings.OutputMode = [NUglify.OutputMode]::MultipleLines
    [NUglify.Uglify]::Html($Content, $Settings).Code
```

![image](https://user-images.githubusercontent.com/15063294/98462155-53dfc000-21b2-11eb-8d65-a425d94777df.png)

Do you have any plans to make this consistent? As I understand for HTML if you would want the same IndentSize 4 you would simply type `"    "`.

**Comment by trullock** [comment]
Yep, this was a known issue, just not to GitHub.

Thanks for raising.

Will address
