### ISSUE TITLE
Multiple HTML tags preserved on one line, when they should be on separate lines with proper indenting

### ISSUE THREAD

**Issue by PrzemyslawKlys** [trullock/NUglify#184]
Excuse my PowerShell

```powershell
    $Settings = [NUglify.Html.HtmlSettings]::new()
    $Settings.RemoveOptionalTags = $false
    $Settings.PrettyPrint = $true
    $Settings.Indent = "`t"
    $Settings.OutputTextNodesOnNewLine = $false # option to not indent textnodes when theyre the only child
    $Settings.JsSettings.MinifyCode = $true
    $Settings.JsSettings.OutputMode = [NUglify.OutputMode]::MultipleLines
    $Settings.CssSettings.IndentSize = 4
    $Settings.CssSettings.OutputMode = [NUglify.OutputMode]::MultipleLines
    $Settings.CssSettings.in
    [NUglify.Uglify]::Html($Content, $Settings).Code
```

```html
				<div class=defaultHeader style="text-align: center;
background-color: #00bfff"><a name="0 section" style="color: #fff">0 section</a><a id=show_1604832152 href=javascript:void(0) onclick='show("1604832152")' style="color: #fff;
display: none">(Show)</a><a id=hide_1604832152 href=javascript:void(0) onclick='hide("1604832152")' style="color: #fff;
display: none">(Hide)</a>
				</div>
```

Output

![image](https://user-images.githubusercontent.com/15063294/98462299-ae2d5080-21b3-11eb-9615-854b53c3af56.png)

**Comment by trullock** [comment]
Theres only half a bug here...

These tags will be kept on the same line, because theyre inline elements by default


                "a",
                "abbr",
                "acronym",
                "b",
                "bdi",
                "bdo",
                "big",
                "button",
                "cite",
                "code",
                "del",
                "dfn",
                "em",
                "font",
                "i",
                "ins",
                "img",
                "kbd",
                "label",
                "mark",
                "math",
                "nobr",
                "q",
                "rp",
                "rt",
                "s",
                "samp",
                "small",
                "span",
                "strike",
                "strong",
                "sub",
                "sup",
                "svg",
                "time",
                "tt",
                "u",
                "var",

Theres a lot of different use cases, but the "half bug" is that there should be a new line after your `<div>` but then they "should" all be on the same line...

Or do you want to see something cleverer where theyre kept on the same line when theres a mix of text nodes and elements, but if all siblings are inline elements, break them onto new lines?

**Comment by PrzemyslawKlys** [comment]
Well, VSCode (which I like for their HTML formatting) is using it the way you describe, or at least partially. Notice that the first `div` is split into separate instances, but the second `div` stays on the same line as the `a` tag. 

![image](https://user-images.githubusercontent.com/15063294/98467015-5f8fae80-21d3-11eb-9ff3-f3688771c203.png)

```html
<div class="defaultSectionHead">
    <div class="defaultSectionText"><a name="Default Section Style">Default Section Style </a>&nbsp;<a id="show_1525574478" href="javascript:void(0)" onclick="show('1525574478'); " style="display:none">(Show)</a><a id="hide_1525574478" href="javascript:void(0)" onclick="hide('1525574478'); ">(Hide)</a></div>
</div>
```

I guess as long as that's compatible I'm happy. However, having it like:

![image](https://user-images.githubusercontent.com/15063294/98467052-8b129900-21d3-11eb-8042-bc891f9f784e.png)

```html
<div class="defaultSectionHead">
    <div class="defaultSectionText"><a name="Default Section Style">Default Section Style </a>
        &nbsp;
        <a id="show_1525574478" href="javascript:void(0)" onclick="show('1525574478'); " style="display:none">(Show)</a>
        <a id="hide_1525574478" href="javascript:void(0)" onclick="hide('1525574478'); ">(Hide)</a>
    </div>
</div>
```

Makes it a bit more readable and you can tell what is happening. I'll accept both, but as you said it would need to be clever enough not to introduce too much splitting into new lines because then it would introduce some other issues.

**Comment by trullock** [comment]
What do you think of the current state of the PR

I need to just do something simple for now, I think this is it.

So unless its buggy I'm gonna go with it.

If you want to have a go at making it better look in `HtmlWriterToHtml`

You need to look at `protected override void Write(HtmlText node)` and `protected override void WriteStartTag(HtmlElement node)`, these are the two places that are relevant to this bug

**Comment by PrzemyslawKlys** [comment]
This is beautiful 

![image](https://user-images.githubusercontent.com/15063294/98485586-d058ba00-2217-11eb-8a89-342c403da7a5.png)

![image](https://user-images.githubusercontent.com/15063294/98485602-efefe280-2217-11eb-98de-0423dbcff802.png)

Thank you. Good enough for me!
