### ISSUE TITLE
Formatting JS code - Opening brace on same line option?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [trullock/NUglify#187]
I know everyone has their own preference for the indentation styles and you can clearly see that there's a top of options out there: https://en.wikipedia.org/wiki/Indentation_style so I'm giving this a shot - maybe it's already there but hidden? 

Your format:
![image](https://user-images.githubusercontent.com/15063294/98485640-24fc3500-2218-11eb-8a04-ad5da8b17ba6.png)

VSCode Format: 
![image](https://user-images.githubusercontent.com/15063294/98485663-3c3b2280-2218-11eb-9582-ef45f5e5fc94.png)

I believe you're using K&R style, and I prefer Variant: 1TBS (OTBS) myself. 

Is it possible? Also when I'm asking about braces, I know you said NUglify strips them to make it "good enough", with the lowest amount of chars, that's why I'm asking if I should bother opening a new issue of making sure there are always braces in place for things like If/Else? In theory in a lot of languages if there's a single line of code under if it's not necessary, but I do prefer to make it clear. Of course - only if it makes sense for you. You already did more than what I imagined would be done.

**Comment by PrzemyslawKlys** [comment]
Just wanted to add for CSS it would make sense to have the same if you will consider this. I can open second issue once it's confirmed one way or the other.

**Comment by trullock** [comment]
yes, make a separate issue for css

**Comment by trullock** [comment]
You want to use this setting:

`public BlockStart BlocksStartOnSameLine { get; set; }`

Technically this ticket is solved because you can use that ^ but I'm going to treat this ticket as the impetus to improve the `Settings` object generally and make OutputMode more obvious to interact with

Theres too many misc `bool`s to magically configure
