### ISSUE TITLE
ShortBooleanAttribute=true incorrectly removes value tags from inputs

### ISSUE THREAD

**Issue by neoGeneva** [trullock/NUglify#19]
The following code generates an incorrectly removes the value from the input. I'm referencing v1.5.5 in .net 
4.6.2.

Example:
```csharp 
Uglify.Html("<input value=\"true\" />");
```

Expected:
```html
<input value=true>
```

Actual:
```html
<input value>
```

**Comment by xoofx** [comment]
Indeed, a side effect for boolean values for normal tags. Don't have time to work on this right now. But PR is welcome.

**Comment by SimplyAdam** [comment]
Was this ever fixed? I still see this happening and wondered if it was made optional?

**Comment by xoofx** [comment]
> Was this ever fixed? I still see this happening and wondered if it was made optional?

Afaik, no, I haven't seen any PR related to this.
