### ISSUE TITLE
Add support for `<% %>` to HTML Parser

### ISSUE THREAD

**Issue by ruicaramalho** [trullock/NUglify#192]
We have a lot of comments and extra spaces is our aspx files. The ideia is to have version of `min.aspx` files.

PS - I know I can use IIS compress to `.gz` but I'm not sure of the performance of this, and is always better to compress a minified file.

**Comment by trullock** [comment]
I presume you mean webforms? Or and old razor version?

Do you want to minify your aspx sources in a one time clean up, or output minified html when they've been rendered?

The latter is probably only a good idea if you're able to use output caching

**Comment by ruicaramalho** [comment]
I mean `webforms` . The idea is when I compile to run run MSBUILD that will minify the aspx file..

But because aspx file can have aspx code like `<%@ Page Title="Computadores" Language="C#"
    MaintainScrollPositionOnPostback="true" %>`, javascript inside `<script>` and CSS inside `<style>` I would bet it will not work?

**Comment by ruicaramalho** [comment]
Just to remove the comments is hard:
 - c# > `<%-- my comment %>`
 - html `<-- coment -->`
 - Js > `\\ coment` or `\* comment *\`
 - css > `\* comment *\`

**Comment by ruicaramalho** [comment]
Another example of aspx:

~~~~ html
<asp:Content ContentPlaceHolderID="MenuLeftPlaceHolder" runat="server">
    <cnt:Button runat="server" GlyphClass="s2b-lampada" ID="Button1" Text="Todos Online?"
        OnClientClick="GetAllOnline();" />
    <cnt:Button runat="server" GlyphClass="s2b-lampada" ID="Button2" Text="Sel. Online?"
        OnClientClick="GetSelectedOnline();" />
    <cnt:Button runat="server" GlyphClass="icon-power" ID="Button3" Text="WOL"
        OnClientClick="WakeSelected();" />
</asp:Content>
~~~~

**Comment by Taritsyn** [comment]
[Dean Hume's HTML Minifier](https://github.com/deanhume/html-minifier) can do these things.

**Comment by trullock** [comment]
I think the only unsupported thing here is removing asp comments `<%-- comment --%>` but we can add that.

As for the rest of this ticket, are you struggling with usage or have you found an actual bug?

**Comment by Taritsyn** [comment]
> c# > `<%-- comment --%>`

What is the point of this if such a comment will never be included in the output HTML?

**Comment by trullock** [comment]
Well, quite

**Comment by trullock** [comment]
Well quite.

It could be useful if you were using NUglify to tidy up all your aspx files in a Linting style operation

**Comment by ruicaramalho** [comment]
I'll make some tests... get back to you with results...

**Comment by ruicaramalho** [comment]
Yes it's complaining about aspx comments...
 > warning : Invalid character '%' following start tag <

**Comment by ruicaramalho** [comment]
Do you have a method to ignore certain text based on regex definition ?

**Comment by ruicaramalho** [comment]
I have used `nuget` to install `Nuglify` but looking into your code on GitHub I thing the error is coming from:

`\html\HtmlParser.cs` > `void TryProcessStartTag()` 

~~~~ csharp
            while(true)
            {
                c = NextChar();
                // TODO: not entirely correct for <? as we should only test for Alpha for the first char
                if (c.IsTagChar() || c == '_' || c == ':' || c == '.' || c == '-') // Plus some special characters not supported by default HTML but used and supported by browsers
                {
                    tempBuilder.Append(c);
                }
                else
                {
                    break;
                }
            }
~~~~

**Comment by trullock** [comment]
Ah ok, so yeah its not handling `<%` like in page directives. 

OK, do you want to submit a PR with some tests?

**Comment by ruicaramalho** [comment]
WORKAROUND... not pretty.. but enough to check does work with HTML parser

~~~~ csharp
    texttominify = texttominify
        .Replace("<%@", "<csharp at")
        .Replace("<%", "<csharp")
        .Replace("%>", "csharp/>");

    UglifyResult uglifyResult = Uglify.Html(texttominify);
    string compressedFileContent = uglifyResult.Code?.Trim();

    compressedFileContent=compressedFileContent
        .Replace("<csharp at", "<%@")
        .Replace("<csharp","<%")
        .Replace("csharp/>","%>");
~~~~

**Comment by trullock** [comment]
Added a PR for this if anyone wants to review, otherwise ill merge in a bit
