### ISSUE TITLE
The nullish coalescing operator cannot be minified

### ISSUE THREAD

**Issue by robertobasile84** [trullock/NUglify#193]
I think that Nuglify breaks when trying to minify something like:

`a = b ?? 'test'`;

**Comment by trullock** [comment]
Can you better define "breaks"?

What input and output are you seeing that you dont expect?

**Comment by robertobasile84** [comment]
Hi,

I just realized that this issue is present in 1.5.11. It is not in the latest version

**Comment by trullock** [comment]
👍 Thought as much

**Comment by robertobasile84** [comment]
Any way we can track back where has been solved? I'm currently stuck with 1.5.11 at the moment

**Comment by trullock** [comment]
https://github.com/trullock/NUglify/blob/master/changelog.md

**Comment by trullock** [comment]
1.6.5 i believe
