### ISSUE TITLE
Strings in V3SourceMap don't get escaped properly

### ISSUE THREAD

**Issue by pmadison** [trullock/NUglify#199]
Moment.js when webpacked produces the following js snippet:

```
/************************************************************************/
/******/ ({

/***/ "./node_modules/moment/locale sync recursive ^\\.\\/.*$":
/*!**************************************************!*\
  !*** ./node_modules/moment/locale sync ^\.\/.*$ ***!
  \**************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

var map = {
	"./af": "./node_modules/moment/locale/af.js",
	"./af.js": "./node_modules/moment/locale/af.js",
	"./ar": "./node_modules/moment/locale/ar.js",
```

When reading this into a V3SourceMap and minifying, I get an incorrectly formatted JSON string for the module:
```
"sources":["moment.js"],
"names":[ ......, "./node_modules/moment/locale sync recursive ^\.\/.*$", ........ ]}
```

Note: it does seem to skip the block comment correctly. I do not get any names in the source map regarding that line.

I am very open to fixing the issue, but I've been digging through the JSParser for a couple of hours now and I'm totally lost. Some direction would be great.

**Comment by trullock** [comment]
Curious

Do have the relevant input snippet which maps to this?

**Comment by pmadison** [comment]
Most of this is still relatively new to me, but I believe this may be what you're looking for? 

https://github.com/moment/moment/blob/b7ec8e2ec068e03de4f832f28362675bb9e02261/moment.js#L2092

Let me know if not.

**Comment by trullock** [comment]
OK,

I assume what youre saying is youre running moment.js through nuglify and getting an unexpected/wrong output?

What we need to do is get to the smallest possible input that produces the erroneous output

So chop down moment.js (maintaining valid, but certainly not functional js) until you get to the smallest possible block of code that doesnt get Nuglified properly, then we can home in on the issue.

If you can then post that input, the output and the expected output that will help us get to the bottom of the issue

**Comment by pmadison** [comment]
Got it. Let's go with:

.js
```
define("moment", [], function() { return (function(modules) { })
({
	/***/ "./node_modules/moment/locale sync recursive ^\\.\\/.*$":
	/*!**************************************************!*\
      !*** ./node_modules/moment/locale sync ^\.\/.*$ ***!
      \**************************************************/
	/*! no static exports found */
	/***/ (function(module, exports, __webpack_require__) { } ) } ) } )
```

actual sourcemap:
```
{
"version":3,
"file":"moment.js",
"mappings":"AAAAA,MAAM,CAAC,QAAQ,CAAE,CAAA,CAAE,CAAE,QAAQ,CAAA,CAAG,CAAE,OAAQ,QAAQ,CAAA,CAAU,EAC5D,CAAC,CACM,wDAAwD,CAKvDC,QAAQ,CAAA,CAAuC,EANtD,CAAD,CADgC,CAA1B",
"sources":["moment.js"],
"names":["define","./node_modules/moment/locale sync recursive ^\.\/.*$"]
}
```

expected sourcemap:
```
{
"version":3,
"file":"moment.js",
"mappings":"AAAAA,MAAM,CAAC,QAAQ,CAAE,CAAA,CAAE,CAAE,QAAQ,CAAA,CAAG,CAAE,OAAQ,QAAQ,CAAA,CAAU,EAC5D,CAAC,CACM,wDAAwD,CAKvDC,QAAQ,CAAA,CAAuC,EANtD,CAAD,CADgC,CAA1B",
"sources":["moment.js"],
"names":["define","./node_modules/moment/locale sync recursive ^\\.\\/.*$"]
}
```

**Comment by trullock** [comment]
OK, so the regex in the names aren't getting minified correctly, right?

**Comment by pmadison** [comment]
Correct

**Comment by trullock** [comment]
Can you show me the exact code youre using to reproduce this?

Are you loading that input JS from a file, or is it pasted directly into some C#?

**Comment by pmadison** [comment]
Sure - I've actually managed to create an exact test in the current version of nuglify that reproduces the error exactly as I'm seeing it in practice. Sorry for not having done this earlier.

I'm not sure the best practice for sharing this, so I'll just paste here for now and if there's a better way please let me know for the future.

1. Create a file with the following contents:
```
define("moment", [], function() { return (function(modules) { })
({
	/***/ "./node_modules/moment/locale sync recursive ^\\.\\/.*$":
	/*! no static exports found */
	/***/ (function(module, exports, __webpack_require__) { } ) } ) } )
```

2. Create a test case with the following contents:
```
        [Test]
        public void MomentParsingExampleTest()
        {
            var path = "C:\\<wherever_you_put_it_or_some_better_way_to_path_to_it>\\Moment-webpacked.js";

            using (var reader = new StreamReader(new FileStream(path, FileMode.Open)))
            {
                using (var mapWriter = File.CreateText(path + ".map"))
                {
                    using (var sourceMap = new V3SourceMap(mapWriter))
                    {
                        sourceMap.StartPackage(path, path + ".min.map");
                        var result = Uglify.Js(reader.ReadToEnd(), path, new CodeSettings { SymbolsMap = sourceMap });
                        Console.WriteLine(result.ToString());
                    }
                }
            }
        }
```

3. Observe that the minified result that gets printed to the console is correct
4. Observe that the sourcemap which was created in moment-webpacked.js.map is incorrect

**Comment by trullock** [comment]
Ughhh you've uncovered a right stinker here.

I think i understand the issue but it needs some further investigation in the morning. I can't tell why this issue isnt more prevalent at the moment, because it seems like it should be...

**Comment by trullock** [comment]
So, there are other issues.

Escape encoding the the source maps seems to be largely broken. I think i've fixed this but it needs a lot of testing

**Comment by pmadison** [comment]
Wow, quick turn around - this is great. I'm so glad you've identified the issue.

Let me know if I can help in any way?

With my limited experience of the library I'm not sure how deep I can go on something like a review, but maybe with some direction I could help out with testing?

Wondering if we should pull out the escape function into a common area. I see the JsonOutputVisitor has it's own version as well, but I think that could be for JSON-specific escaping so I can see how it could also make sense to leave that.  https://github.com/trullock/NUglify/blob/65a2ffac78e784a6eeacdfb600b209a039012b4f/src/NUglify/JavaScript/Visitors/JsonOutputVisitor.cs#L685

**Comment by trullock** [comment]
So there's only so many places in the sourcemap that there could be escaping issues, any of the value strings basically so any way to have a \ in them (e.g. paths) or any of the identifier names.

I'll consult the JSON one too then, sourcemap are JSON so they should use the same escaper. And JSON is JavaScript so they should also use the same escaper!

**Comment by trullock** [comment]
So the `JsonOutputVisitor` is also broken, it doesnt encode properly. We'll fix that whilst we're at it

**Comment by trullock** [comment]
Fxied in 1.11.3

**Comment by pmadison** [comment]
Thank you!
