### ISSUE TITLE
Object Property Shorthand breaks when properties are the only reference to a locally scoped variable

### ISSUE THREAD

**Issue by iskewedI** [trullock/NUglify#200]
Whilst Object Property Shorthand syntax is supported normally => 

> `const foo = "1234";`
> `const dummy = "5678";`
>  `const  obj = { foo, dummy };`
>  `console.log(obj.foo); `
>  `console.log(obj.dummy); `

Minified =>
 **`const foo="1234",dummy="5678",obj={foo,dummy};console.log(obj.foo);console.log(obj.dummy) //This works!`** 

If you try to do the same in the returning object of a function (used frecuently with IIFE) => 

> `const obj = (function(){ `
> ` const dummy = "1234"; `
> `  const foo = "1235";`
> ` return { foo, dummy } ` 
>  `})();`

Minified => 
**`const obj=function(){return{"1235","1234"}}() //You get an error!`**

**Comment by trullock** [comment]
Ok that's odd, IL take a look asap

**Comment by trullock** [comment]
This is a bug in `ActivationObject.SingleReferenceVariableField`.

It doesn't care about the reference being an `ObjectLiteralProperty`, which it needs to on line `650`

**Comment by trullock** [comment]
Can you check if this PR works for you?

**Comment by iskewedI** [comment]
> Can you check if this PR works for you?

Excelent! Now is working, thank you!

**Comment by trullock** [comment]
ok great, im not sure the fix is 100% complete so if you find any variations that are also broken, reopen this with details please.

This fix is in v1.11.1
