### ISSUE TITLE
Object destructuring syntax on function parameter with default values doesn't work with Arrow Functions

### ISSUE THREAD

**Issue by iskewedI** [trullock/NUglify#201]
Combining object destructuring and default property value:

The only parameter in **sum** function is an object, with two default properties with their default values 2 and 3, respectively.
- `const sum = function( { foo = 2, dummy = 3 } ){ return console.log(foo + dummy )};`
`sum( {} )` Expected: 2 + 3 = 5
`sum( { foo: 1 } )` Expected: 1 + 3 = 4

That works well, but if you try to do the same but with Arrow Function syntax _**() => {}**_  ->
- `const sum = ( { foo = 2, dummy = 3 } ) => console.log(foo + dummy);`

That code returns the **UglifyResult** with _HasErrors_ = **True** and the _Errors_ =
_**Error message**_: Unable to convert from reference to binding: foo = 2
_**Subcategory**_: run-time

_**Error message**_: Unable to convert from reference to binding: dummy = 3
_**Subcategory**_: run-time

**Comment by trullock** [comment]
Should be an easy fixes given Functions already support this.

Will take a look ASAP

**Comment by trullock** [comment]
The problem is that `ParseObjectLiteral` is not invoked with `isBindingPattern=true` when parsing arrow functions, because the parser naively doesnt think its an arrow function by this point.

It needs to always assume so, and then after parsing handle cases when it found bindings that it didnt expect.

**Comment by trullock** [comment]
Workaround for now is not to use `=` in the object literal in the arrow function arguments, this will take some work to fix

**Comment by iskewedI** [comment]
> Workaround for now is not to use `=` in the object literal in the arrow function arguments, this will take some work to fix

Ok!
