### ISSUE TITLE
ES6 computed property name's minification doesn't work for function parameter

### ISSUE THREAD

**Issue by experdot** [trullock/NUglify#204]
Run the following code
``` csharp
    class Program
    {
        static void Main(string[] args)
        {
            var source = "function(args){console.log(args.data.name);console.log({[args.data.name]:0})}";
            Console.WriteLine(NUglify.Uglify.Js(source));
            Console.ReadKey();
        }
    }
```

The 2rd `args` reference is not replaced:
``` js
function(n){console.log(n.data.name);console.log({[args.data.name]:0})}
```

**Comment by colonelchlorine** [comment]
Just bumped into this myself and thought I was going crazy in my TypeScript compilation. Reproduced the same example. Tried with `Uglify.Js(Script, new CodeSettings { NoAutoRenameList = "require", ScriptVersion = ScriptVersion.EcmaScript6 })` and no luck. Here's a link to reproduction with NUglify 1.11.3: https://dotnetfiddle.net/mqiAPE

**Comment by trullock** [comment]
Found it!

>>>// don't care about the property names; just recurse the values

**Comment by trullock** [comment]
Made a PR, can you guys give this a whirl, make sure ive caught all variations of the bug

**Comment by colonelchlorine** [comment]
Thanks for the quick help @trullock! Tested it locally and it solves the problem 👍. Still getting stuck on template literals, but leave that for another day/issue.

**Comment by trullock** [comment]
Whats up with template literals?

**Comment by colonelchlorine** [comment]
@trullock Should have mentioned tagged template literals specifically. Created a new issue (#210) with example & expected output. Seems like it got commented out in unit tests. Find this ES6 'feature' awkward & haven't been a fan ... but there it is lol.

**Comment by trullock** [comment]
Ha great thanks for the details, let's chat on #210
