### ISSUE TITLE
Formatting or Minifying fonts breaks code

### ISSUE THREAD

**Issue by PrzemyslawKlys** [trullock/NUglify#209]
```html
<style>
    .fa-500px:before {
        content: "\f26e";
    }

    .fa-accessible-icon:before {
        content: "\f368";
    }

    .fa-accusoft:before {
        content: "\f369";
    }

    .fa-acquisitions-incorporated:before {
        content: "\f6af";
    }

    .fa-ad:before {
        content: "\f641";
    }

    .fa-address-book:before {
        content: "\f2b9";
    }

    .fa-address-card:before {
        content: "\f2bb";
    }

    .fa-adjust:before {
        content: "\f042";
    }

    .fa-adn:before {
        content: "\f170";
    }

    .fa-adversal:before {
        content: "\f36a";
    }
</style>
```

Formatting this or minifying returns:

```html
<html>
    <head>
        <style>
            .fa-500px:before {
                content: ""
            }
            .fa-accessible-icon:before {
                content: ""
            }
            .fa-accusoft:before {
                content: ""
            }
            .fa-acquisitions-incorporated:before {
                content: ""
            }
            .fa-ad:before {
                content: ""
            }
            .fa-address-book:before {
                content: ""
            }
            .fa-address-card:before {
                content: ""
            }
            .fa-adjust:before {
                content: ""
            }
            .fa-adn:before {
                content: ""
            }
            .fa-adversal:before {
                content: ""
            }
        </style>
    </head>
</html>
```

As you remember I'm doing it from PowerShell but I doubt it matters. 

```powershell
    $Settings = [NUglify.Html.HtmlSettings]::new()
    # HTML Settings
    if ($IsFragment) {
        $Settings.IsFragmentOnly = $true
    }
    $Settings.RemoveOptionalTags = $RemoveOptionalTags.IsPresent
    $Settings.PrettyPrint = $true
    $Settings.Indent = $Indent
    $Settings.OutputTextNodesOnNewLine = $OutputTextNodesOnNewLine.IsPresent # option to not indent textnodes when theyre the only child
    $Settings.RemoveEmptyAttributes = $RemoveEmptyAttributes.IsPresent
    $Settings.AlphabeticallyOrderAttributes = $AlphabeticallyOrderAttributes.IsPresent
    $Settings.RemoveComments = $RemoveComments
    $Settings.RemoveQuotedAttributes = $false
    #$Settings.LineTerminator = [System.Environment]::NewLine
    # JS Settings
    $Settings.JsSettings.MinifyCode = $true
    $Settings.JsSettings.OutputMode = [NUglify.OutputMode]::MultipleLines
    $Settings.JsSettings.Indent = $Indent
    $Settings.JsSettings.BlocksStartOnSameLine = $BlockStartLine
    $Settings.JsSettings.PreserveFunctionNames = $true
    $Settings.JsSettings.LocalRenaming = [NUglify.JavaScript.LocalRenaming]::KeepAll
    #$Settings.JsSettings.EvalTreatment = [NUglify.JavaScript.EvalTreatment]::Ignore
    #$Settings.JsSettings.Format = [NUglify.JavaScript.JavaScriptFormat]::Normal
    $Settings.JsSettings.NoAutoRenameList = $true
    $Settings.JsSettings.PreserveFunctionNames = $true
    #$Settings.JsSettings.CollapseToLiteral = $true
    #$Settings.JsSettings.ConstStatementsMozilla = $true
    #$Settings.JsSettings.LineBreakThreshold = 50
    $Settings.JsSettings.ReorderScopeDeclarations = $false
    #$Settings.JsSettings.RenamePairs = $false
    #$Settings.JsSettings.QuoteObjectLiteralProperties = $true
    $Settings.JsSettings.TermSemicolons = $true
    # $Settings.NoAutoRenameCollection  # ReadOnly
    #$Settings.JsSettings.LineTerminator = "`r`n"
    # CSS Settings
    $Settings.CssSettings.OutputMode = [NUglify.OutputMode]::MultipleLines
    $Settings.CssSettings.Indent = $Indent
    $Settings.CssSettings.BlocksStartOnSameLine = $BlockStartLine
    $Settings.CssSettings.RemoveEmptyBlocks = $RemoveEmptyBlocks
    #$Settings.CssSettings.LineTerminator = "`r`n"
    [NUglify.Uglify]::Html($Content, $Settings).Code
```

**Comment by PrzemyslawKlys** [comment]
Ok, it seems disabling `$Settings.CssSettings.DecodeEscapes = $false` fixes the issue. Question should it be even default?

**Comment by trullock** [comment]
Well this isnt necessarilly an issue, it just happens that the codepoints used for feather icons dont have a visual representation in your IDE/consoles font

**Comment by PrzemyslawKlys** [comment]
It is an issue - my as my powershell code writes it down the way it was returned. When I apply this to all.css and later on try to use it in my code I can't see anything. 

I've opened an issue on StackOverflow to later realize it displays wrong font because of minimization

![image](https://user-images.githubusercontent.com/15063294/101019604-82f90f80-356d-11eb-811f-5f6e65901108.png)


https://stackoverflow.com/questions/65079416/font-awesome-inline-within-single-portable-html-file

**Comment by trullock** [comment]
Why would you decode? Because `\f369` is 5 codepoints where as what it represents is probably less

Try it with a visible codepoint first to see if its your powershell - which I think it is because there are tests covering this

try:

`    content: "\1f92f";`

and see what gets output by what youre doing

**Comment by PrzemyslawKlys** [comment]
That's what I got:

![image](https://user-images.githubusercontent.com/15063294/101825097-76f0ed00-3b2d-11eb-9433-96ef93afa118.png)

The difference is  - at least as far as I understand it - it would work properly if I would have loaded those fonts up on my system (be a developer of it) and simply was preparing a package for someone to use it. The moment I simply try to take any html/css out from internet and minify it - it's gonna be broken. At least that's how I understand what happens.

**Comment by trullock** [comment]
I don't think we're on the same page here..

take this

```
    .fa-500px:before {
        content: "\f26e";
    }
````

`f26e` in the unicode space falls in Private Use Area https://unicode-table.com/en/blocks/private-use-area/ where none of the glyphs have a representation (which is why you're seeing a square).

The exploding head `1f92f` does have a visual representation, an exploding head. Which is why your IDE font has something to show.

You havent shown anything is broken, just discovered that not all codepoints have a visual representation.

Try the css, does it work? I bet it does

**Comment by PrzemyslawKlys** [comment]
The font that is broken doesn't work - hence why I came running with an issue. 

![image](https://user-images.githubusercontent.com/15063294/101827316-73129a00-3b30-11eb-8276-1a910b8f9daf.png)

The last image is a font that's "minified" with decode escapes enabled.

**Comment by trullock** [comment]
Can you make a repos with a before/after that i can look at?

Just a small blob of html, css and the font

**Comment by PrzemyslawKlys** [comment]
I just tried and I can't reproduce it anymore. I don't understand what's happening. It works both ways with the all.css I've prepared.

**Comment by trullock** [comment]
I suspect you had your own encoding issues, not saving the file with the right encoding or treating the nuglify output improperly.

Come back with an example if you can repeo anything 🙂
