### ISSUE TITLE
Tagged template literals not working

### ISSUE THREAD

**Issue by colonelchlorine** [trullock/NUglify#210]
Running into an issue with tagged template literals when compiling to ES2015/ES6. I saw the unit test for tagged template literals is commented out in ES2015 tests: https://github.com/trullock/NUglify/blob/1f6e9be2d8a07b1d7154020d34be64450b50e55b/src/NUglify.Tests/JavaScript/ES2015.cs#L69. I saw in git history Sam noted that "6 tests fail for various reasons so are commented out". Let me know if you need any other info, or if anything's inaccurate.

Sample code using NUglify 1.11.4 (can run here: https://dotnetfiddle.net/txPdSY)
```
using System;
using NUglify;
using NUglify.JavaScript;
public class Program
{
	public static string Script = @"
		function translate(strings, ...values) {
			return strings.reduce((acc, s, i) => {
				acc += s;
				if (values[i]) {
					acc += values[i];
				}
				return acc;
			}, """");
		}
		let script = ""ES2015"";
		console.log(translate `Here's an ${script} example`);";

	public static void Main()
	{
		Console.WriteLine(Uglify.Js(Script, new CodeSettings { ScriptVersion = ScriptVersion.EcmaScript6 }).Code);
	}
}
```

Output
```
function translate(n,...t){return n.reduce((n,i,r)=>(n+=i,t[r]&&(n+=t[r]),n),"")}let script="ES2015";console.log(translate);script;example`);
```

Expected result (I think)
```
function translate(n,...t){return n.reduce((n,i,r)=>(n+=i,t[r]&&(n+=t[r]),n),"")}let script="ES2015";console.log(translate `Here's an ${script} example`);
```

**Comment by trullock** [comment]
Added a PR which might fix this

Can you enrich 

https://github.com/trullock/NUglify/blob/bug_210/src/NUglify.Tests/TestData/JS/Input/ES2015/TaggedTemplates.js

and the corresponding

https://github.com/trullock/NUglify/blob/bug_210/src/NUglify.Tests/TestData/JS/Expected/ES2015/TaggedTemplates.js

with as many other tagged template use cases you can think of?

**Comment by trullock** [comment]
Merging and closing. Reopen if you have a case that is still broken
