### ISSUE TITLE
HtmlToText doesn't recognize <br/> in html format

### ISSUE THREAD

**Issue by MinicLakic** [trullock/NUglify#211]
When I am having some html format that contains <br/> tag, it doesn't recognize it.
For example : `<p>Hello</p><p>This is a test<br/>This is another test</p><p>&nbsp;</p><p>Something</p>` 
In this case, after executing HtmlToText with KeepStructure option, it gives me aggregated:
'Hello\nThis is a testThis is another test\n \nSomething'.
Do you have some fix for this?

**Comment by trullock** [comment]
Fixed in 1.11.5

If you don't think its doing exactly what you want, please modify/copy this test which demonstrates your problem and desired outcome

https://github.com/trullock/NUglify/blob/master/src/NUglify.Tests/Html/Bugs.cs#L199

**Comment by MinicLakic** [comment]
When will be release?

**Comment by trullock** [comment]
It should already have been but I can see it hasnt....

Something must be wrong with AppVeyor...

I'll look now
