### ISSUE TITLE
"Setter must have a single parameter" for "set" functions in classes that aren't setters.

### ISSUE THREAD

**Issue by rwasef1830** [trullock/NUglify#215]
Hello,
Example in this function:
https://github.com/matteobruni/tsparticles/blob/4340750b22588bc764845f58b2848377b20ca9ee/core/main/src/Core/Loader.ts#L71

It is minified fine and works in the browser, however it generates error JS1315 setter must have a single formal parameter when it is actually not a setter... just a function called "set".

**Comment by trullock** [comment]
Thanks for the report.
Can you provide a succinct JavaScript example of the error you are experiencing?

**Comment by rwasef1830** [comment]
@trullock 

```js
export class Loader {
    set(not, a, setter) {
        alert(not + a + setter);
    }
}
```

will produce the error

**Comment by trullock** [comment]
Brilliant thanks. 

I'm sure I fixed this recently.....

Will take a look asap

**Comment by trullock** [comment]
Has this come from BundlerMinifier? What version of NUglify are you using?

**Comment by notsure2** [comment]
Yes, but I forked it and update NUglify to v1.11.5 and it still generates the same error. I even had to implement ignoreErrorList in my fork to get an output from it.

**Comment by rwasef1830** [comment]
Yes, and I forked it, to use NUglify v1.11.5 I have a failing test case in master.

**Comment by trullock** [comment]
Link me, I cant repro

**Comment by rwasef1830** [comment]
https://github.com/rwasef1830/NUglify/tree/bug-215 @trullock
