### ISSUE TITLE
[Bug] Some tags and quotation marks (within meta tags) missing after minification

### ISSUE THREAD

**Issue by pbru87** [trullock/NUglify#227]
### Environment
NUglify version: **1.13.1**

### Bug description
I have the following HTML document which I would like to minify:
```
<!DOCTYPE html>
<html lang="de-DE">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>Hello World!</title>
	</head>
	<body>
		<div>
			Hello World!
		</div>
	</body>
</html>
```

C# | I call the NUglify HTML method like this:
```
using NUglify;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace HomepageBuilder
{
    static class UtilityClass
    {
        public static void MinifyHTML(string htmlFilePath)
        {
            string htmlMarkup = File.ReadAllText(htmlFilePath, Encoding.Default);
            var result = Uglify.Html(htmlMarkup);
            File.WriteAllText(htmlFilePath, result.Code, Encoding.Default);
        }
    }
}
```
The HTML output looks like this:
```
<!DOCTYPE html><html lang=de-DE><meta charset=utf-8><meta name=viewport content="width=device-width, initial-scale=1"><title>Hello World!</title><div>Hello World!</div>
```
**So what is wrong with the output?**
* The `<head>` tag is missing completly.
* The closing `</body>` and `</html>` tags are missing.
* The `<html>` and the `<meta>` tags are missing some quotation marks.

**Comment by trullock** [comment]
Its been..... minified! :D

**Comment by pbru87** [comment]
Hi @trullock, thanks for your quick reply! I actually thought this would be a bug behavior. After I read your message, I found more information about optional HTML tags [here](https://google.github.io/styleguide/htmlcssguide.html#Optional_Tags). So, thanks for your clarification!

**Comment by trullock** [comment]
No problem!

Any issues, come right back :)
