### ISSUE TITLE
V3SourceMap object in NUglify nuget package not up to date for Source Map spec

### ISSUE THREAD

**Issue by sgjoy1** [trullock/NUglify#23]
I'm using the NUglify nuget package (v1.5.5) in my solution, and I'm seeing a problem with the V3SourceMap object that the package brings with it. The V3SourceMap object adds a property for lineCount. However, per the [V3 SourceMap specification](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.ue4jskhddao6), that property has been removed. Can the V3SourceMap in the NUglify nuget package be updated to be more in line with the spec (i.e. removing that property)?

**Comment by xoofx** [comment]
Don't have time to work on this, but a PR is welcome

**Comment by trullock** [comment]
Shipped in v1.8.1
