### ISSUE TITLE
Color with no value and important throws an error

### ISSUE THREAD

**Issue by angelcalvasp** [trullock/NUglify#252]
Hello there,

The current css that I found on a theme fails to minify because it expects a value
```css
.text-inverse-muted {
  color: !important;
}
```

I have minified this online and in some cases it was minified and other cases the whole line was ignored

I tried to modify the CssParser to let this value pass, but perhaps the best way is to just ignore the whole line which I tried to do but to no avail, since I have failed to understand the worker completely

For the minification I did the following and it worked, but not sure if this is the way, all css tests passed
![image](https://user-images.githubusercontent.com/7502746/118175847-a1a5e100-b3fe-11eb-907c-663381a5e9c2.png)

**Comment by trullock** [comment]
Thanks for the report.

Yeah this is invalid and also meaningless so should be removed during minification.

I'll take a look

**Comment by angelcalvasp** [comment]
:D thanks

**Comment by trullock** [comment]
Can you show me the code you're using which throws?

`master` doesn't throw, it does report an error as per line 2262 in your screenshot above.

This is desired, the CSS is erroneous so its reporting an error.

Or do I misunderstand?

**Comment by angelcalvasp** [comment]
I Apologize, It was my mistake, it was not NUGlify that was throwing the exception it was a wrapper I will close
