### ISSUE TITLE
Static properties in javascript not supported

### ISSUE THREAD

**Issue by PoulBak** [trullock/NUglify#260]
I have the following simple class with static properties: 

class VindueType extends Number
{
    static Vent = 0;
    static Tom = 1;
    static Besked = 2;
    static Bekræft = 3;
    static Spørg = 4;
    static Indtast = 5;
    static Fil = 6;
};

When running the minifier, I get this:

class VindueType extends Number{static Vent = 0{static;Tom=1;static;Besked=2;static;Bekræft=3;static;Spørg=4;static;Indtast=5;static;Fil=6}

As you can see, it adds a left curly bracket after '0' and semi colon after the 'static' keyword - now there's one too many left curly brackets!
Now it's not valid javascript.

It's actually easy to fix, when ever you see the 'static' you should only remove white space, otherwise leave it as it is.
I know that static isn't part of the standard yet, but all browsers support it, check here: [Link to Mozilla static](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static)

**Comment by trullock** [comment]
This is really a specific case of #235 , which is not yet implemented and needs to be

**Comment by PoulBak** [comment]
Yes, it look that way. However, this was my very first file using NUglify and it actually crashed with a null exception. I split up the file in smaller bits, then it at least showed the errors. I mean, crashing is BAD, right?

**Comment by trullock** [comment]
Absolutely. I am but a lowly 2nd generation maintainer of this project, not the author.

I want to get around to looking at this, i might get time in a few weeks. Otherwise, PRs welcome!

**Comment by trullock** [comment]
Closing this as its basically #235 which I'm working on now
