### ISSUE TITLE
Case insensitive CSS selector not supported, causes crash

### ISSUE THREAD

**Issue by mattscotty** [trullock/NUglify#270]
As outlined [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors), I've tried using a case insensitive selector in CSS;
`[fill="#21386D" i]`

However, this results in the following error;
**Message: Expected closing bracket, found 'i'**

From what I can tell, this should be supported as its now widely implemented [across most modern browsers](https://caniuse.com/css-case-insensitive).

Thanks

**Comment by trullock** [comment]
Thanks for the bug report

**Comment by trullock** [comment]
Worth adding that all of i, I, s and S should be supported.

**Comment by trullock** [comment]
Fixed in 1.14.0
