### ISSUE TITLE
Strict-mode does not allow assignment to undefined variables

### ISSUE THREAD

**Issue by rochapablo** [trullock/NUglify#272]
After minify, I get the following error

```
Strict-mode does not allow assignment to undefined variables: regeneratorRuntime
```

https://github.com/formium/tsdx/issues/1071
https://stackoverflow.com/questions/68801520

**Comment by trullock** [comment]
Re your SO post, is this actually an issue?

**Comment by trullock** [comment]
Closing this as non-issue. Reopen with justification if you think its valid
