### ISSUE TITLE
Add option to stop removing curly brackets for blocks with only one statement.

### ISSUE THREAD

**Issue by rpgkaiser** [trullock/NUglify#273]
The _minifier_ is failing to minify JavaScript code with blocks that contains a single statement, when this statement correspond to a **const** or **let** declaration, like 
`if (a){
  const b = 5;
}`
Because the _minifier_ is removing the _curly brackets_ when it finds a block with a single statement.
So, it would be great if we have an option (temporarily) to stop removing those _curly brackets_.
Thanks.

**Comment by trullock** [comment]
Hmm, curious. There is code to deal with this. Are you on the latest version? 

Can you provide your exact (as small as possible) input, how you're invoking NUglify, and the output?

**Comment by rpgkaiser** [comment]
Ok, let me check the version in use...well...I'm actually facing this issue while using BundlerMinifier.Core v3.2.499, so, the installed version of the NUglify was 1.5.14.
I'll upgrade to the latest version to verify.
Thanks.

**Comment by rpgkaiser** [comment]
No luck...after updating NUglify to version 1.14.0 I'm getting the same error. But I'm pretty sure now that the issue wont happen with the latest version.
Thanks.

**Comment by trullock** [comment]
Ok, reopen this if latest NUglify still had the error
