### ISSUE TITLE
Object destructuring fails when not declaring variable inline

### ISSUE THREAD

**Issue by jdom** [trullock/NUglify#290]
The following code:
```
let foo, bar;
({foo, bar} = {foo: 42, bar: true});
```
becomes:
```
let foo,bar;({foo,bar})={foo:42,bar:!0}
```
Expected:
```
let foo,bar;({foo,bar}={foo:42,bar:!0})
```

Notice how the closing parenthesis (which *are required* here in javascript, since it's not declaring and initializing the variable inline) were shifted from enclosing the whole assignment, to just enclosing the left-hand side of the destructuring expression (which is wrong). The expected minified code is:
```
let foo,bar;({foo,bar}={foo:42,bar:!0})
```

Nevertheless the following minifies correctly:
```
const {foo, bar} = {foo: 42, bar: true};
```
Becomes:
```
const{foo,bar}={foo:42,bar:!0}
```

**Comment by trullock** [comment]
fixed in 1.17.9

**Comment by jdom** [comment]
w00t! thanks for fixing it! I started troubleshooting but this one was a little bit more complex than other bugs I fixed. Thanks again

**Comment by trullock** [comment]
i mean, dont look at the code its a diabolical hack haha
