### ISSUE TITLE
JS minification variable name conflicts with functions in nested blocks

### ISSUE THREAD

**Issue by mattscotty** [trullock/NUglify#299]
Using 1.17.10, I'm encountering issues with variable names being generated during minification of JavaScript.
I'm using the following C# code to minify HTML pages;

```
string htmlCode = Uglify.Html(System.IO.File.ReadAllText(fileName)).Code;

string newFileName = fileName.Replace(".html", ".min.html");

File.WriteAllText(newFileName, htmlCode);
```

There seems to be an issue occurring within nested functions inside a nested block where minified variable names are repeated causing loss of access to outer variables.

Example **original code**;

```
    {
        const elForm = document.getElementById('editForm');
        const elBtnLogin = document.getElementById('btnLogin');
        const elEmail = document.getElementById('Email');
        const elPassword = document.getElementById('Password');
        const elValMsg = document.getElementById('valMsg');
        const elLoginLoadingText = document.getElementById('divLoginLoadingText');

        function onSubmit(data) {
            const status = {
                zero: 0,
                one: 1,
                two: 2,
                three: 3
            };

            let checker;

            switch (parseInt(data.status)) {
                case status.zero:
                    checker = 1;
                    break;
            }

            return checker;
        }
    }
```
**Minified Code;**

```
{
    const n = document.getElementById("editForm"),
        t = document.getElementById("btnLogin"),
        i = document.getElementById("Email"),
        r = document.getElementById("Password"),
        u = document.getElementById("valMsg"),
        f = document.getElementById("divLoginLoadingText");

    function e(n) {
        let t;
        switch (parseInt(n.status)) {
            case {
                zero: 0,
                one: 1,
                two: 2,
                three: 3
            }.zero:
                t = 1
        }
        return t
    }
}
```

As we can see, the variable names are being repeated which is removing access to variables outside of the function (in the original code we can see 'btnLogin', this becomes 't', but 't' is used again within the function, this shouldn't happen).
Its a similar case with 'n' which is declared as the element for 'editForm' and as the inner variable name for the function.

**Expected output** (something like) no conflicts;
```
{
    const n = document.getElementById("editForm"),
        t = document.getElementById("btnLogin"),
        i = document.getElementById("Email"),
        r = document.getElementById("Password"),
        u = document.getElementById("valMsg"),
        f = document.getElementById("divLoginLoadingText");

    function e(n) {
            const o = {
                zero: 0,
                one: 1,
                two: 2,
                three: 3
            };

        let g;
        switch (parseInt(n.status)) {
            case o.zero:
                g = 1
        }
        return g
    }
}
```

Thanks

**Comment by trullock** [comment]
Reading on my phone so forgive me.
I can't see a problem in the minified code. Yes outer scope variables are hidden by inner ones, but the outer ones aren't used? So there's no problem?

**Comment by trullock** [comment]
Umm can you provide some actual erroneous input/output code then pls?

**Comment by mattscotty** [comment]
After some further investigation I can confirm that its unlikely there is an issue here.
Weird issues in safari led me down the wrong rabbit hole.

Once I saw that the variables were being repeated, I thought that was the issue, however I think you're correct in that this only occurs if said variables are not used further down the line.

[StackOverflow](https://stackoverflow.com/a/68315172/2311918) came to the rescue, adding "use strict" resolved the problem.

Apologies for the confusion and thank you for your time.

**Comment by trullock** [comment]
No problem

There have been bugs where variables have been incorrectly overridden, and its likely some more remain.

Can you elaborate on adding "use strict", as maybe theres an opportunity to improve the docs or something

**Comment by mattscotty** [comment]
According to SO, [this Mozilla article about block level functions in non-strict code ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions#block-level_functions_in_non-strict_code) seems to explain best.
For me, it only seemed to affect Safari, though I did not test in Firefox.
