### ISSUE TITLE
Need a downloadable exe file

### ISSUE THREAD

**Issue by ylazy** [trullock/NUglify#3]
I just want to use NUglify as a command line tool on Windows. Where can I get a downloadable exe file?

Thanks!

**Comment by Garfield550** [comment]
@ylazy 
You can clone this project, open the NUglifyApp project in Visual Studio and compile it.

![snipaste_2017-12-26_17-07-21](https://user-images.githubusercontent.com/3471836/34352747-48759b6e-ea5f-11e7-8974-f8ef10868037.png)

**Comment by ylazy** [comment]
@Garfield550 Thank you! As I can see, you're using the option "-out" to specify the output path. Please tell me where you get the list of command line options?

**Comment by Garfield550** [comment]
@ylazy On `MainClass.cs` file, `ProcessArgs method` region code block
https://github.com/xoofx/NUglify/blob/bbc4bf41d9d0ca353f62992c7ce3afd6f19ac77e/src/NUglifyApp/MainClass.cs#L320-L650

**Comment by ylazy** [comment]
@Garfield550 wow! thank you so much 🌼
