### ISSUE TITLE
Invalid yield after JS minification

### ISSUE THREAD

**Issue by jbress** [trullock/NUglify#300]
Hello,

This
```if (!(yield isOk(p * n))) { ... }```

Becomes this
```if (!yield t(n * r)) { ... }```

which is not valid (throws "Unexpected identifier" error)

Expecting
```if (!(yield t(n * r))) { ... }```

The input javascript code is transpiled via TypeScript 4.3 with ES2015 target (Visual Studio 2019)
Full code attached
[1 input.js.txt](https://github.com/trullock/NUglify/files/8199281/1.input.js.txt)
[2 output actual.js.txt](https://github.com/trullock/NUglify/files/8199282/2.output.actual.js.txt)
[3 output expected.js.txt](https://github.com/trullock/NUglify/files/8199283/3.output.expected.js.txt)
[source.ts.txt](https://github.com/trullock/NUglify/files/8199284/source.ts.txt)

**Comment by trullock** [comment]
Thanks for the report, will take a look

**Comment by jbress** [comment]
Great. Thanks for this project btw

Note that I could only reproduce the problem when combining if-not with for-loop.

Meanwhile, is there any setting/workaround to "disable" the removal of the parenthesis ?

**Comment by trullock** [comment]
Fixed in 1.17.11

**Comment by jbress** [comment]
Thank you !
