### ISSUE TITLE
Add "application/json" to the list of processable javascript type blocks

### ISSUE THREAD

**Issue by AndyMcKenna** [trullock/NUglify#303]
Using version 1.17.10

**Description**
Script blocks with type `application/json` are not getting minified to a single line.  If I change the type to `application/ld+json` it all works.

**To Reproduce**
Input contains 
`<script id=priceStakDataModel type=application/json>  
  {"selectedTab":"buy"}  
</script>`

**Minified output or stack trace**
![minifiedoutput](https://user-images.githubusercontent.com/29063167/157280837-7add3a11-7655-46b4-9444-2fc058593e57.PNG)

**Excepted output code**
`<script id=priceStakDataModel type=application/json>{"selectedTab":"buy"}</script>`

I'm planning to submit a PR for this as it's an extension of #66

**Comment by trullock** [comment]
Fixed in 1.18.0
