### ISSUE TITLE
String.raw causes NUglify to throw exception

### ISSUE THREAD

**Issue by PoulBak** [trullock/NUglify#305]
Are you using the latest verion of NUglify, especially if used through BunderMinifier? Update before raising a bug as your issue is probably already fixed.
Yes, just upgrade to 1.17.13
**Describe the bug**
This line produces an exception inside NUglify.dll.
**To Reproduce**
Provide a minimal source code example AND how you are invoking NUglify
`    let udenfor = String.raw``\\.$^{[(|)*+?abcdefknprstuvwx\d``;
`
(the backticks are doubled here so it looks correct - there should of course only be one at each end)
**Minified output or stack trace**
Provide the minfied code which is erroneous or the stack trace in case of an exception
'Identifier expected"
**Excepted output code**
Provide the expected minified code
It should simple output the same line.

**Comment by trullock** [comment]
Will take a look

a workaround is probably to add parenthesis e.g. `String.raw(``bla``)`

**Comment by trullock** [comment]
no, youre right

**Comment by PoulBak** [comment]
Hehe, this so typical javascript, yet another exception to the syntax rules :-)

**Comment by trullock** [comment]
Yeah i really hate this syntax. Makes no sense and is completely unnecessary

**Comment by PoulBak** [comment]
Well, the 'good' news are, that the syntax in only used when it contains exactly `String.raw```and ends with a backtick. The parser should just ignore it, since it can't compress this in any way.

**Comment by PoulBak** [comment]
Wow, that was a fast fix, looking forward to try it.

**Comment by PoulBak** [comment]
Good new and bad news.
It works with 'String.raw' except, when the string contains an interpolated string, like:

```
let tempVar = 'b';
let a = String.raw`${tempVar}`;
```

**Comment by PoulBak** [comment]
Well, at least there's an easy workaround here:  simply split the string, like:
    String.raw`aaa` + tempVar + String.raw`bbb`
