### ISSUE TITLE
Possible bug minifying CSS when using HEX content value

### ISSUE THREAD

**Issue by norcino** [trullock/NUglify#308]
I tested with the latest version of the code here in master.

**Describe the bug**
The minification produces the wrong result when an input is provided with HEX character value

**To Reproduce**
```
var css = ".something: before { content: \"\\E900\"; }";
 
Console.WriteLine($"Minifying: {css}");

var minifiedCss = NUglify.Uglify.Css(css);

Console.WriteLine($"Minified css: {minifiedCss}");
```

**Minified output or stack trace**
_.something: before{content:"?"}_

**Excepted output code**
.something: before{content:"\E900"}

**Comment by norcino** [comment]
Not a bug, it looks like this is the behaviour by design, to address this issue I used the following:

```
var cssSettings = new CssSettings();
cssSettings.DecodeEscapes = false;
var minifiedCss = NUglify.Uglify.Css(css, cssSettings);

```

**Comment by trullock** [comment]
Your workaround should arguably be the default, not going to break everyone's world by flipping this though
