### ISSUE TITLE
Add ability to disable tags being converted to lower case in HtmlSettings

### ISSUE THREAD

**Issue by mattscotty** [trullock/NUglify#311]
Currently HTML tags are converted to lower case when using Uglify.Html().
To take into account case sensitive tags that may be being read by another app which is case sensitive (e.g. when minifying XML), a new setting should be added to HtmlSettings, similar to AttributesCaseSensitive.
E.g.

`NUglify.Html.HtmlSettings { TagsCaseSensitive = true }`

**Comment by trullock** [comment]
Fixed in 1.20.0
