### ISSUE TITLE
Missing CSS optimizations

### ISSUE THREAD

**Issue by SpeednetGroup** [trullock/NUglify#313]
I recently switched from using a [home-grown CSS compressor ](https://www.lotterypost.com/css-compress.aspx) to NUglify and noticed that the minified file size was larger using NUglify.

I then compared the output produced by each and came up with a number of missing CSS optimizations in NUglify.

- The space before `!important` can be removed.
- Color representations should be converted to words if the word is shorter.  For example, `#808080` should be `gray` and `#f00` should be `red`.  Same for RGB and other color formats.  All colors (except when they include an opacity component) should be reduced to the smaller of either the word or the 6- or 3-digit color code.
- All instances of `0%` should be `0`.
- `border:none` should be `border:0`.
- `@supports (` (and other similar queries) should have no space - i.e., `@supports(`.
- `font-weight:bold` should be `font-weight:700`.
- Declarations that use a top, right, bottom, and left size should be reduced by eliminating redundant values.  For example, `margin:15px 0 0 0` should be `margin:15px 0 0`.

There might be some others, but this is what I came up with in a first pass.

**Comment by trullock** [comment]
Ok these are great thanks

Can you break them down into separate issues?

Thanks

**Comment by SpeednetGroup** [comment]
I'd be happy to -- but just want to be sure that you want a separate issue for each bullet point above.  i.e., create a separate issue for "space before !important", etc.

**Comment by trullock** [comment]
Yes please

**Comment by SpeednetGroup** [comment]
OK, no problem, will do this a bit later.

**Comment by SpeednetGroup** [comment]
Closed because each point was separated into its own issue.
