### ISSUE TITLE
Missing CSS optimization - using '0' instead of 'none'

### ISSUE THREAD

**Issue by SpeednetGroup** [trullock/NUglify#317]
Please update the CSS optimizations in NUglify to user `border:0` instead of `border:none`. They are functionally equivalent.

This optimization should apply to the following rules:

- border
- border-top
- border-right
- border-bottom
- border-left
- outline

**Comment by trullock** [comment]
is `border: 0` the same as `border: 0px`

**Comment by SpeednetGroup** [comment]
> is `border: 0` the same as `border: 0px`

It is the same as zero of any units.  It could be 0px, 0em, 0%, etc.  `0` is equivalent to all of them, which is why you never need units on a zero value.
