### ISSUE TITLE
Stackoverflow Exception occur on malformed html / deep level html

### ISSUE THREAD

**Issue by taufik-alto** [trullock/NUglify#32]
Hi.

I am using the _HtmlToText_ function and has run in some issues with the above exception. As the above exception can't be caught;; the application will crashed.

Sample site html - [http://www.skyhobbies.com.sg/pagelink_radio_systems.html](http://www.skyhobbies.com.sg/pagelink_radio_systems.html)

Possible to add a depth level counter limit?

Using [W3C markup validation service for the site](https://validator.w3.org/check?uri=http%3A%2F%2Fwww.skyhobbies.com.sg%2Fpagelink_radio_systems.html&charset=%28detect+automatically%29&doctype=Inline&group=0), shows the errors
for e.g., Line 349, Column 728: **number of open elements exceeds TAGLVL (100)**

**Comment by xoofx** [comment]
Indeed, the minifier is stack based, will check when I will have a bit of spare-time to migrate to a non-stack based HTML nodes traversal

**Comment by trullock** [comment]
I'm gonna close this. I'm not swapping out the HTML parser for such a sadistic edge case, but I'll take a PR if anyone's volunteering 👍
