### ISSUE TITLE
CSS Minification Breaks Flexbox for IE11

### ISSUE THREAD

**Issue by tiy-curtissimo** [trullock/NUglify#33]
When minifying a CSS file, given the statement `flex: 1 0 0px` as a setting, NUglify removes the `px` and leaves `flex: 1 0 0` which does not correctly work on IE11.

**Comment by BagusTesa** [comment]
Hi, it seems this problem did not plague flex, but almost all css rules that have px at the end of the expression. For example:

```
@-webkit-keyframes Floating {
  0% {
    -webkit-transform: translate(0%, 0px)
  }
  50% {
    -webkit-transform: translate(0%, 15px)
  }
  to {
    -webkit-transform: translate(0%, 0px)
  }
}
```

turns into
```
@-webkit-keyframes Floating {
  0% {
    -webkit-transform: translate(0%, 0)
  }
  50% {
    -webkit-transform: translate(0%, 15px)
  }
  to {
    -webkit-transform: translate(0%, 0)
  }
}
```

This issue seems to be carried from the roots (Microsoft.AjaxMinifier).

**Comment by trullock** [comment]
@BagusTesa are you sure that's an invalid case? I don't think it is :/
