### ISSUE TITLE
HtmlToText - KeepStructure

### ISSUE THREAD

**Issue by ThiloL** [trullock/NUglify#34]
HtmlToText option "KeepStructure" should care about Paragraphs and Line breaks. Right?

**Comment by xoofx** [comment]
> HtmlToText option "KeepStructure" should care about Paragraphs and Line breaks. Right?

Not sure what you imply by "care", but re-reading the code, it should not remove/change line breaks and keep them in the output html...

**Comment by ThiloL** [comment]
I mean "<br>" in the source should result in a "\n" in the result string. And "<p>...</p>" should generate an "\r\n" in the result string.

**Comment by xoofx** [comment]
I'm not sure it keeps the original `\n` in all cases, typically here:

https://github.com/xoofx/NUglify/blob/39e851bf70a2746d5a25a67eb4ebb0c404700d9f/src/NUglify/Html/HtmlWriterToText.cs#L100-L104

so it looks like it keeps the structure, but it doesn't keep the exact same binary convention. Sorry this is some code I haven't touched for the fast year, so don't recall the full details 😅

**Comment by trullock** [comment]
What's the exact issue being reported here?

Can you provide an input, output and expected output example please?

**Comment by trullock** [comment]
Closing this

Reopen with expected/actual outputs and a description of any bug
