### ISSUE TITLE
"border: 0 none;" is optimized with invalid css

### ISSUE THREAD

**Issue by failwyn** [trullock/NUglify#343]
`border: 0 none;` is minified to `border: 0 0;` 0 is not a valid value for border-style. This appears to be a side effect of the optimization added to fix [#317](https://github.com/trullock/NUglify/issues/317)

**Minified output or stack trace**
`border: 0 0;`

**Excepted output code**
`border: 0 none;`

**Comment by trullock** [comment]
feel free to make a PR that reverses #317 and we can reopen that with this in mind, or make the PR to fix this :)
