### ISSUE TITLE
run-time error JS1292: Strict-mode does not allow duplicate property names: =

### ISSUE THREAD

**Issue by zhangyiatmicrosoft** [trullock/NUglify#345]
The latest release 1.20.3.
This is similar to #279 

**Describe the bug**
NUglify rejects object default values.

**To Reproduce**
Make a simple js with the following content and feed to NUglifyApp.exe:
<code>'use strict'; class TinySDF { constructor({ fontSize = 24, buffer = 3, radius = 8, cutoff = 0.25, fontFamily = 'sans-serif', fontWeight = 'normal', fontStyle = 'normal' } = {}) { } }</code>

**Minified output or stack trace**
D:\repo\GitHub\NUglify\src\NUglifyApp\bin\Debug\TinySDF.js(1,67-68): run-time error JS1292: Strict-mode does not allow duplicate property names: =
D:\repo\GitHub\NUglify\src\NUglifyApp\bin\Debug\TinySDF.js(1,79-80): run-time error JS1292: Strict-mode does not allow duplicate property names: =
D:\repo\GitHub\NUglify\src\NUglifyApp\bin\Debug\TinySDF.js(1,91-92): run-time error JS1292: Strict-mode does not allow duplicate property names: =
D:\repo\GitHub\NUglify\src\NUglifyApp\bin\Debug\TinySDF.js(1,110-111): run-time error JS1292: Strict-mode does not allow duplicate property names: =
D:\repo\GitHub\NUglify\src\NUglifyApp\bin\Debug\TinySDF.js(1,137-138): run-time error JS1292: Strict-mode does not allow duplicate property names: =
D:\repo\GitHub\NUglify\src\NUglifyApp\bin\Debug\TinySDF.js(1,159-160): run-time error JS1292: Strict-mode does not allow duplicate property names: =

**Excepted output code**
It should process without error

**Comment by zhangyiatmicrosoft** [comment]
The above is the simplified version and the original full class is at https://github.com/mapbox/tiny-sdf/blob/main/index.js

**Comment by zhangyiatmicrosoft** [comment]
@trullock Any chance you can prioritize this severe bug? This is a common practice and the gramma is legit from ES2015.

**Comment by trullock** [comment]
Pull requests are very welcome

**Comment by trullock** [comment]
Fixed in 1.20.5
