### ISSUE TITLE
Boolean logic

### ISSUE THREAD

**Issue by automagisk** [trullock/NUglify#35]
Hi, unfortunately I get this strange issue with rewritten logic in javascript. I have nailed it down to this particular expression that gets rewritten into something that is not equivalent.

A js-file with just this code: !a || b

gets rewritten to: a&&b

which I believe is not the same. Does anyone know why? Can I turn this feature off to begin with?

**Comment by trullock** [comment]
I cant repro this, are you able to? I've made a PR with a test. If you can make that test fail, I'll take a look.

Otherwise I'll close this
