### ISSUE TITLE
Execute the formatting code, but the error cannot be caught using try catch

### ISSUE THREAD

**Issue by colindcli** [trullock/NUglify#359]
The code.zip compressed package contains a js test file. When using the above code `var setting = CodeSettings.Pretty(); Uglify.Js(code, setting);` to format js, an error is reported. The error message is `$exception {"Exception_WasThrown"} System.StackOverflowException` 
I use try catch, but the error cannot be caught, and the program crashes directly.

[code.zip](https://github.com/trullock/NUglify/files/11189744/code.zip)

```
try{
    var setting = CodeSettings.Pretty(); 
    //Use the js file in the code.zip compressed package 
    Uglify.Js(code, setting);
} catch(Exception e){
    //but can't catch the error
}
```

The main problem is that the catch cannot catch the error

_Originally posted by @colindcli in https://github.com/trullock/NUglify/issues/355#issuecomment-1537273276_

**Comment by trullock** [comment]
You need to provide me a sensible code sample that can actually be comprehended.

How do you expect anyone to debug that obfuscated madness?

What are you hoping to achieve, minifying already minified and obfuscated code?

**Comment by colindcli** [comment]
js 代码非常长，大小有750kb

**Comment by colindcli** [comment]
Format js error
