### ISSUE TITLE
Feature request: new option to disable collapsing colors to #rgb(a)

### ISSUE THREAD

**Issue by hpetriffer** [trullock/NUglify#369]
At the moment there is no possibility to disable collapsing colors to #rgb(a). This collapsing in our case makes some problems. Is it possible to add some setting to disable this?
The method CrunchHexColor has already an parameter to disable the behaviour.
I can provide a pull request if desired.

**Comment by trullock** [comment]
Yeah send me a PR

**Comment by trullock** [comment]
Fixed in 1.21.0
