### ISSUE TITLE
Is it possible to provide a ScriptBundle implementation?

### ISSUE THREAD

**Issue by chucklu** [trullock/NUglify#373]
As the ScriptBundle from Assembly [System.Web.Optimization](https://www.nuget.org/packages/Microsoft.AspNet.Web.Optimization), Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
does not work for js file [datatables.min.js.zip](https://github.com/microsoft/ajaxmin/files/13237676/datatables.min.js.zip) , which is downloaded from site https://datatables.net/download/

packages\Microsoft.AspNet.Web.Optimization.1.1.3\lib\net40\System.Web.Optimization.dll
```c#
  bundles.Add(new ScriptBundle("~/admin/js").Include("js file path");
```

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.Ajax.Utilities.Member.GetFunctionGuess(AstNode target)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.GuessAtName(AstNode node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(FunctionObject node)
>    at Microsoft.Ajax.Utilities.FunctionObject.Accept(IVisitor visitor)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(BinaryOperator node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(Block node)
>    at Microsoft.Ajax.Utilities.TreeVisitor.Visit(IfNode node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(IfNode node)
>    at Microsoft.Ajax.Utilities.IfNode.Accept(IVisitor visitor)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(Block node)
>    at Microsoft.Ajax.Utilities.TreeVisitor.Visit(IfNode node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(IfNode node)
>    at Microsoft.Ajax.Utilities.IfNode.Accept(IVisitor visitor)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(Block node)
>    at Microsoft.Ajax.Utilities.TreeVisitor.Visit(IfNode node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(IfNode node)
>    at Microsoft.Ajax.Utilities.IfNode.Accept(IVisitor visitor)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(Block node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(FunctionObject node)
>    at Microsoft.Ajax.Utilities.FunctionObject.Accept(IVisitor visitor)
>    at Microsoft.Ajax.Utilities.TreeVisitor.Visit(CallNode node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(CallNode node)
>    at Microsoft.Ajax.Utilities.CallNode.Accept(IVisitor visitor)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(Block node)
>    at Microsoft.Ajax.Utilities.JSParser.InternalParse()
>    at Microsoft.Ajax.Utilities.Minifier.MinifyJavaScript(String source, CodeSettings codeSettings)
>    at System.Web.Optimization.JsMinify.Process(BundleContext context, BundleResponse response)
>    at System.Web.Optimization.Bundle.ApplyTransforms(BundleContext context, String bundleContent, IEnumerable`1 bundleFiles)
>    at System.Web.Optimization.Bundle.GetBundleResponse(BundleContext context)
>    at System.Web.Optimization.BundleResolver.GetBundleContents(String virtualPath)
>    at System.Web.Optimization.AssetManager.EliminateDuplicatesAndResolveUrls(IEnumerable`1 refs)
>    at System.Web.Optimization.AssetManager.RenderExplicit(String tagFormat, String[] paths)
>    at ASP._Page_Views_Shared__AdminLayout_cshtml.Execute() in 
> _AdminLayout.cshtml:line 29
>    at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
>    at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
>    at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
>    at System.Web.WebPages.WebPageBase.<>c__DisplayClass40_0.<RenderPageCore>b__0(TextWriter writer)
>    at System.Web.WebPages.WebPageBase.Write(HelperResult result)
>    at System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body)
>    at System.Web.WebPages.WebPageBase.PopContext()
>    at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
>    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
>    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
>    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
>    at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult)
>    at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
>    at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState)
>    at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
>    at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
>    at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
>    at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
>    at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)
>    at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
>    at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
>    at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
>    at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
>    at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

   
   The file was downloaded from https://datatables.net/download/index

**Comment by chucklu** [comment]
The exception was thrown from [WebGrease](https://www.nuget.org/packages/WebGrease/), however nobody is maintaining the WebGrease library.
I  have test the above js file with your library, it does not throw exception.
I am not sure how to write a ScriptBundle based on your lib, any advice?
It will be appreciative if you can implement a ScriptBundle to replace the old lib [System.Web.Optimization](https://www.nuget.org/packages/Microsoft.AspNet.Web.Optimization) and [WebGrease](https://www.nuget.org/packages/WebGrease/)，as none of them are actively maintained.

**Comment by trullock** [comment]
Bundling has nothing to do with minification, so you should be able to clone an existing bundle implementation and then swap out the last step of minification to use NUglify. I can take a look at code you get into this state but I dont have time to do it for you from scratch

**Comment by chucklu** [comment]
@trullock  there are three Bundle classes in System.Web.Optimization.dll

> Use Bundle if you need to bundle JavaScript or CSS files, but you do not need to minify them.
> Use ScriptBundle if you need to bundle JavaScript files and minify them.
> Use StyleBundle if you need to bundle CSS files, merge them, and specify media types for each file

The issue I encounter is, I am using the .min.js file with ScriptBundle class
I just avoid the issue by switch to use Bundle class(which will not trigger the process of minification)

However there might still be problem with the ScriptBundle class in  System.Web.Optimization.dll
