### ISSUE TITLE
Run-time errors and incorrect output when using variable named "module" after a "let"

### ISSUE THREAD

**Issue by dylanstreb** [trullock/NUglify#375]
Originally discovered through BunderMinifier, but reproduced in the latest master code (caa68d0). I'm running through the App program, i.e. `NUglifyApp.exe example.js`.

**Describe the bug**
Accessing a variable named `module` after the use of `let` results in erroneous syntax error warnings. In the actual application this later led to a NullReferenceException, but this script does not reproduce that.

I believe this is related to #94 and #80.

Changing `let abc` to `var abc` gets rid of the error. Changing the variable name to anything other than module also removes the error. `let module` also causes the issue. Putting another "let" after all references to module does not cause an error.

#94 mentions "const" instead of "let"; I didn't try that but I assume it will cause the issue. Other keywords might do the same.

**To Reproduce**
```JavaScript
function func() {
  var module;
  
  let abc = 'text';

  module = {};
  module.data = "text";
  module["data2"] = 5;
}
```

**Minified output or stack trace**
This results in the minified output:
```JavaScript
function func(){var n;module{}n.data="text";module{}["data2"]=5}
```

as well as the following errors:

```
C:\Local\example.js(6,10-11): run-time error JS1010: Expected identifier: =
C:\Local\example.js(6,10-11): run-time error JS1195: Expected expression: =
C:\Local\example.js(8,9-10): run-time error JS1010: Expected identifier: [
```

Line 7 is not reported as an error, but everything else that accesses module is.

**Excepted output code**
Changing the `let` to `var` results in:
```JavaScript
function func(){var n;n={};n.data="text";n.data2=5}
```

and no errors. The extra `module{}` blocks are not included. Renaming the variable does the same thing.

**Comment by trullock** [comment]
Thats really odd....

Does it still output errors if you turn renaming/crunching off?

**Comment by dylanstreb** [comment]
> Thats really odd....
> 
> Does it still output errors if you turn renaming/crunching off?

As in `NUglifyApp.exe -rename:none -minify:false example.js`?

Same errors. Output is `function func(){var module;let abc='text';module{}{};module.data="text";module{}["data2"]=5}`, which still has the `module{}` block.

**Comment by trullock** [comment]
I'll take a look, this has intrigued me...

**Comment by trullock** [comment]
Right, its because your variable is called `module`. Workaround for now is to not call it `module`. I'll look at a fix

**Comment by trullock** [comment]
Fixed in 1.21.1

**Comment by MaceWindu** [comment]
@trullock btw, 1.21.1 release wasn't published due to build error on CI

**Comment by trullock** [comment]
Oops, republishing as 1.21.2
