### ISSUE TITLE
selector token not support

### ISSUE THREAD

**Issue by ArgoZhang** [trullock/NUglify#383]
Are you using the latest verion of NUglify, especially if used through BunderMinifier? Update before raising a bug as your issue is probably already fixed.

**Describe the bug**
throw error unexpected token `selector(`

**To Reproduce**
```
@supports not selector(::-webkit-scrollbar) {
    .scroll {
        scrollbar-color: rgba(0,0,0,0.3) rgba(0,0,0,0);
        scrollbar-width: thin;
    }
}
```

**Minified output or stack trace**

```
Unexpected token, found 'selector('
```

**Excepted output code**

**Comment by trullock** [comment]
Is that even valid css?

https://developer.mozilla.org/en-US/docs/Web/CSS/@supports#formal_syntax

**Comment by ArgoZhang** [comment]
![image](https://github.com/trullock/NUglify/assets/22001478/d7406e7e-7a05-48ef-8d87-9646a459c404)

I think that is valid CSS.

thank you for the quick replay

you can find in the follow URL
https://developer.mozilla.org/en-US/docs/Web/CSS/@supports#testing_for_the_support_of_a_selector

**Comment by trullock** [comment]
Fair enough

`CssParser` should be easy to modify to handle this. Submit a PR

**Comment by ArgoZhang** [comment]
@trullock  thanks, release a BootstrapBlazor.NUglify package for own project.
