### ISSUE TITLE
How do I use the NUglify.Tasks.dll

### ISSUE THREAD

**Issue by oneilsoftware-phutton** [trullock/NUglify#387]
We are currently using AjaxMin to minify and combine CSS files but it doesn't support some new CSS features that we want to use so we need to use something else. We are calling AjaxMin using MSBuild by referencing AjaxMin.Tasks.dll. This AjaxMin.Tasks.dll was included in the AjaxMin NuGet package but NUglify.Tasks.dll is not included in it's NuGet package. I see that it exists in the source code though.

If I want to use NUglify to minify CSS files using MSBuild, do I have to build NUglify myself to get NUglify.Tasks.dll?

**Comment by trullock** [comment]
I haven't used NUglify.Tasks since taking over this project.

Yes you'll need to build it yourself, although theres no reason it cant go into a published nuget. PRs welcome
