### ISSUE TITLE
Ability to have conditional comments in html for minification

### ISSUE THREAD

**Issue by CheloXL** [trullock/NUglify#5]
This is a suggestion/question and not a bug per se. I would like to be able to have something similar (to what AjaxMin had in js) to the #if DEBUG //#else //#endif in my html code, that of course would need to work with some kind of conditional comments. 

In that way, I can reference my non bundled, non minified files when running in debug mode, and have references to the .min css/js files.

Please note that the "running in debug mode" here is just a preference and it is not related at all with the running environment.

Example:

```
<!--[if MINIMIZE]>
    <script src="js/bundle.min.js"></script>
<![endif]-->
<![if !MINIMIZE]>
    <script src="js/library1.js"></script>
    <script src="js/library2.js"></script>
    <script src="js/application.js"></script>
<![endif]>
```

So, when fetching the non-minified page, the browser will execute what's inside the !MINIMIZE section, and when minimized, that section is removed and the code inside the MINIMIZE section is promoted from the comment.

**Comment by xoofx** [comment]
In which context are you using HTML minification? For static files? I'm just wondering because most of the time, the if/endif in HTML is typically handled at a higher level (by the templating system, for example, in Razor view, the bundler depending on its configuration will output the bundle.min.js or individual files)

**Comment by CheloXL** [comment]
Yes, in static html files. When server side rendering is available, of course I can handle that from there.
Specifically, I have a bunch of applications that are hosted over self-hosted services using owin selfhost and serving files using the owin staticfiles plugin. I'm pre-processing all my assets (less/css, js) at build time, but I don't have a way to do the above with html files.
Right now I have two lines, one that links to the (for example) .js file, and another to the .min.js file, and I manually switch between them before I do the build, but it is too easy for me to forget about that (not even mention if someone else takes over the project).

**Comment by trullock** [comment]
Why would you want part of the HTML unminified, got an example to help me understand?

**Comment by trullock** [comment]
I agree with @xoofx here, this should be a concern of your view engine.

For example, when do you expect `if !MINIMIZE` to run? When you're _not_ putting the HTML through the minifier?...


If we wanted to stop the minifier minifying a block of HTML, id either do this:

```
<nuglify-no-minify>
    ... contents here
</nuglify-no-minify>
```

And have the minifier remove the start and end tag of `nuglify-no-minify` but keep its content untouched, or have a `nuglify-no-minify` property/attribute on tags and this would cause the minifier to ignore the tag.

All that said, I don't really see a case for this. If the minifier is messing up a node then thats a bug, your example isnt a minification problem, its a view engine problem.

Closing for now, reopen with a good counter argument :)
