### ISSUE TITLE
ES2015 + ES2017 support

### ISSUE THREAD

**Issue by samjudson** [trullock/NUglify#52]
This issue covers area of ES2015 and ES2017 which do not minify correctly.

Each task is the name of the test (which is currently commented out). The reason for the test failing may only be a small part of the feature.

ES2015

- [ ] Task Templates
- [ ] Modules
- [ ] Class Inheritance Assignment
- [ ] Class Inheritance Expressions
- [ ] Iterators/For-Each
- [ ] Proxying

ES2017

- [x] Async/Await

**Comment by rockstardev** [comment]
I think this is great format and it gives us clear path to closing lots of issues. Thanks for taking lead on this... for those not informed, here is PR showing tests @samjudson added: https://github.com/xoofx/NUglify/pull/51

**Comment by trullock** [comment]
Where are we up to with this? It looks like a lot of it is in place, how accurate is this ticket still?

**Comment by samjudson** [comment]
No idea to be honest, I've lost track of most of the changes recently. Happy to close the issue though.

**Comment by trullock** [comment]
I'll close this then. if we find anythting missing or broken we can reopen or make a new ticket
