### ISSUE TITLE
Js minification breaks generators

### ISSUE THREAD

**Issue by CheloXL** [trullock/NUglify#57]
When minifying js code that has generators, even if I specify the precedence with grouping, the minified version doesn't work.

For example, this code
```javascript
if (description != null) {
	(yield Speech.speak(description, token));
}
```
is being minified as:
```javascript
n != null && yield Speech.speak(n, u);
```
that of course will not work as && has higher precedence than yield so the above evaluates as (n != null && yield) Speech.speak(n, u);. That then throws `Uncaught SyntaxError: Unexpected strict mode reserved word` where the method is declared as I'm using "use strict".

Ref: madskristensen/BundlerMinifier/issues/378

**Comment by trullock** [comment]
Quick thought whilst im at this, i bet await suffers the same bug...
