### ISSUE TITLE
[HTML] Remove data-* attributes

### ISSUE THREAD

**Issue by Crissov** [trullock/NUglify#59]
It is sometimes helpful to remove custom attributes prefixed with `data-`, or any non-recognized attribute.

- in: `<p data-foo="bar">baz</p>`
- out: `<p>baz</p>`

babelmark/babelmark.github.io#3

**Comment by trullock** [comment]
how is this different to #61?

**Comment by trullock** [comment]
Closing this, I consider the fix to #60 which shipped in 1.7.2 to have fixed this. Reopen if there's good reason to be a separate issue 👍

**Comment by Crissov** [comment]
I raised this issue for custom, user-defined attributes, while #60 and #61 are mostly about predefined Standard attributes. Anyway, thanks for addressing all of these.
