### ISSUE TITLE
[HTML] Reorder HTML attributes

### ISSUE THREAD

**Issue by Crissov** [trullock/NUglify#60]
It's more a matter of prettyfying, but anyway: a canonical order of attributes can be helpful, fall back to alphabetical order.

- in: `<img src="foo" alt="bar" title="baz"/>`
- out: `<img alt="bar" src="foo" title="baz"/>`

babelmark/babelmark.github.io#3

**Comment by trullock** [comment]
Shipped in 1.7.2
