### ISSUE TITLE
[HTML] Remove user-supplied attributes

### ISSUE THREAD

**Issue by Crissov** [trullock/NUglify#61]
Sometimes you don't care about all those IDs and classes or some other attributes, so want to ditch them. Which ones are to be removed is up to the user configuration.

- in: `<div id="foo" class="bar" title="baz">quuz</div>`, `['id', 'class']`
- out: `<div title="baz">quuz</div>`

babelmark/babelmark.github.io#3

**Comment by trullock** [comment]
Shipped in 1.7.2
