### ISSUE TITLE
uglify js leaves multiline strings as is

### ISSUE THREAD

**Issue by vinaybr** [trullock/NUglify#70]
Hi,

By default multiline strings (`....`) are left as is. Is there an option to compress these as well.

**Comment by nul** [comment]
@vinaybr are you talking about template literals (using backticks) or ES5 multiline syntax? Can you include a sample of what you're after?

**Comment by trullock** [comment]
Added tests for both syntaxes and both are minified sensibly.

Closing this.

Reopen with repro details if an issues still exists
