### ISSUE TITLE
Bugs on css calc 

### ISSUE THREAD

**Issue by sugiarto-dvd** [trullock/NUglify#74]
bugs on minify html like this : 

`<div style="width:calc(100%);height:calc(100vh - 0px);overflow-y:auto;position:relative;">test<div>`

it will be minified to
`<div style="width:calc(100%);height:calc(100vh - 0);overflow-y:auto;position:relative;">test<div>`

it make this div not showing because invalid height.

**Comment by wasigh** [comment]
I have the same problem.  A workaround seems to be to replace the 0px with 0%. See: https://github.com/xoofx/NUglify/blob/fa44e619627fec7c5fd602d8df42129fb59c6782/src/NUglify/Css/CssScanner.cs#L1047

**Comment by trullock** [comment]
This is probably the same as #33, and should be reviewed together

**Comment by trullock** [comment]
Interestingly Resharper has this same bug, its suggests the `px` are redundant

**Comment by trullock** [comment]
@sugiarto-dvd @wasigh @tiy-curtissimo @BagusTesa this PR fixes your reported cases.
