### ISSUE TITLE
ParseKeyFrames - missing on error recovery

### ISSUE THREAD

**Issue by BulletMagnet76** [trullock/NUglify#75]
In CssParser.ParseStyleSheet() there are two while loops that parse each type of token.  The first while loop includes ParseKeyFrames() .  The entire file should be parsed after this loop.  If it is not, there is another loop: while (!m_scanner.EndOfFile)  that keeps looping until the end.  Inside is another copy of the parsing while loop.
However, this second copy of the parsing loop does not include ParseKeyFrames().  So if there is any error in the file, keyframes will not be included in the result.
![Annotation 2019-08-14 162809](https://user-images.githubusercontent.com/54123216/63060809-8831d700-beb0-11e9-8e2b-5d6cda92178f.png)

**Comment by trullock** [comment]
@BulletMagnet76  Do you have a test case that produces an error associated with this?
