### ISSUE TITLE
Syntax error on valid regular expression /[^]/

### ISSUE THREAD

**Issue by Lizzy-Gallagher** [trullock/NUglify#78]
The following regular expression works in JavaScript (at least in Chrome and IE): /[^]/ but NUgilfy fails when parsing it with a run-time syntax error.

This expression is valid in ECMAScript (it is essentially "."), but is not recognized by C# even with RegexOptions.ECMAScript set (as NUglify does in https://github.com/xoofx/NUglify/blob/d975ebc375a2fa46473900fca8ed7691d0ac86a1/src/NUglify/JavaScript/Visitors/AnalyzeNodeVisitor.cs#L3459). See https://github.com/dotnet/corefx/issues/41546.

**Comment by trullock** [comment]
So this looks like a bug in dotnet, which also looks to have been fixed since you raised this. I've made a PR which contains a test for this case which passes. If you can verify this and/or modify the PR/test to make it fail that would be helpful 👍 

https://github.com/xoofx/NUglify/pull/100

**Comment by trullock** [comment]
This wasn't necessarily fixed properly due to an issue with the NUglify test suite.

This needs testing by consuming the NUglify.dll in a modern .NET core app.

Not sure where Core's fix applies, whether its at compile time or runtime. Could also depend on how nuget delivers the dll

**Comment by trullock** [comment]
This seems to be broken in .NET Framework, not much to do be done here, simply need to use the updated/fixed Core versions
