### ISSUE TITLE
CSS Grid named lines cause Expected Expression error

### ISSUE THREAD

**Issue by OneThatWalks** [trullock/NUglify#82]
## Expected Behavior
When processing css with grid template containing area/line names (see below for example) there should be no errors.

```
#grid2 {
    grid-template-columns: [col-start] 1fr [col-end];
}
```

## Current Behavior
When processing above css I receive a `Expression Expected` error with the token being '[' from the `[col-start]` block.

## Possible Solution
Update the css parser to allow for square brackets for potential grid definitions.

## Steps to Reproduce
1. Create a css file with above styling
2. Execute the built NUglify app against the file
I used the following in the bin folder `.\NUglifyApp.exe -analyze -out -css .\test.css`

## Context
NUglify is used in the BuildBundleMinifier project to bundle and minify js/css and alike.  When writing css grids for a project I ran into this bug that prevented the minification.  In my case I disabled the bundleminifier step for this file to get around the issue.

## Detailed Description
CSS Grid allows for the naming of areas within a grid (https://www.w3.org/TR/css-grid-1/#grid-line).  When doing so you can use the names to position elements inside the grid.  This works in most modern browsers and minification would only need to remove unnecessary white-space. 

## Possible Implementation
I have done some digging in the CssParser and the error occurs at line 2455.  The code is trying to parse an expression, which from my understanding of the code, the grid line names are not.  My thoughts are to update the ParseTerm to look at '[' similar to '('.

**Comment by trullock** [comment]
I can't repro this in tests

Ive added a test here if you want to modify it to repro your issue, otherwise maybe its already been fixed?
